grails-app/domain/com/item/Car.groovy
package com.item

class Car {
  String year
  String model
  String make
  Date date = new Date()

    static constraints = {
      year  blank: false
      model  blank: false
      make (inList:['Toyota', 'Hyundai', 'VW'])
    }
}

grails-app/domain/org/company/Employee.groovy
package org.company

class Employee {
    String name
    String position
    Double salary
    Integer phoneNumber
    String email
    String dob

      static constraints = {
          name blank: false
          position inList: ["Clerk","Manager","Supervisor"], blank: false
          salary blank: false, range: 900..2300
          phoneNumber blank: false, unique:true, matches: '^(\\(?\\+?[0-9]*\\)?)?[0-9_\\- \\(\\)]*$'
          email email:true, blank: false, unique:true
        }
}

grails-app/controllers/com/item/CarController.groovy
package com.item

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = false)
class CarController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Car.list(params), model:[carCount: Car.count()]
    }

    def show(Car car) {
        respond car
    }

    def create() {
        respond new Car(params)
    }

    @Transactional
    def save(Car car) {
        if (car == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (car.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond car.errors, view:'create'
            return
        }

        car.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'car.label', default: 'Car'), car.id])
                redirect car
            }
            '*' { respond car, [status: CREATED] }
        }
    }

    def edit(Car car) {
        respond car
    }

    @Transactional
    def update(Car car) {
        if (car == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (car.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond car.errors, view:'edit'
            return
        }

        car.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'car.label', default: 'Car'), car.id])
                redirect car
            }
            '*'{ respond car, [status: OK] }
        }
    }

    @Transactional
    def delete(Car car) {

        if (car == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        car.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'car.label', default: 'Car'), car.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'car.label', default: 'Car'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/itemsystem/UrlMappings.groovy
package itemsystem

class UrlMappings {

    static mappings = {
        "/$controller/$action?/$id?(.$format)?"{
            constraints {
                // apply constraints here
            }
        }

        "/"(view:"/index")
        "500"(view:'/error')
        "404"(view:'/notFound')
    }
}

grails-app/controllers/org/company/EmployeeController.groovy
package org.company

import grails.transaction.Transactional

@Transactional(readOnly = false)
class EmployeeController {

  def index() {
    def employee = Employee.list()

       [emp:employee]
  }

  def create() {
    respond new Employee(params)
  }

  @Transactional
  def save(Employee employee) {
    if (employee == null) {
            notFound()
            return
        }

    if (employee.hasErrors()) {
            respond employee.errors, view:'create'
            return
        }

    employee.save flush:true
    redirect action: 'index'
  }

  def edit(Employee employee) {
    respond employee
  }

  @Transactional
  def update(Employee employee) {
    if (employee == null) {
        notFound()
        return
    }

    if (employee.hasErrors()) {
        respond employee.errors, view:'edit'
        return
    }
    employee.save flush:true
    redirect action: 'index'
  }

  def show(Employee employee) {
    respond employee
  }

  @Transactional
  def delete(Employee employee) {
    if (employee == null) {
            notFound()
            return
        }

    employee.delete flush:true
    redirect action: 'index'
  }

  protected notFound(){
    redirect action: "index"
  }
}

grails-app/views/car/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'car.label', default: 'Car')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-car" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-car" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.car}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.car}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.car}" method="POST">
                <fieldset class="form">
                    <f:all bean="car"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/car/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'car.label', default: 'Car')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-car" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-car" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.car}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.car}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.car}" method="PUT">
                <g:hiddenField name="version" value="${this.car?.version}" />
                <fieldset class="form">
                    <f:all bean="car"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/car/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'car.label', default: 'Car')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-car" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-car" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${carList}" />

            <div class="pagination">
                <g:paginate total="${carCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/car/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'car.label', default: 'Car')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-car" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-car" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="car" />
            <g:form resource="${this.car}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.car}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/employee/create.gsp
<!DOCTYPE html>
<html>
  <head>
    <meta name="layout" content="master"/>
    <title>Add Employee</title>
  </head>
  <body>
    <div class="col-md-8 col-md-offset-2">

      <g:form controller="employee" action="save" class="form-horizontal">
        <fieldset>

          <!-- Form Name -->
          <legend>New Employees Registration Form</legend>

          <!-- Text input-->
          <div class="form-group">
            <label class="col-md-4 control-label" for="name">Name</label>
            <div class="col-md-4">
              <input id="name" name="name" type="text" value="${employee.name ?: ''}" class="form-control input-md" required></div>
            </div>

            <!-- Select Basic -->
            <div class="form-group">
              <label class="col-md-4 control-label" for="position">Position</label>
              <div class="col-md-4">
                <select required id="position" name="position" class="form-control">
                  <option value="Clerk">Clerk</option>
                  <option value="Manager">Manager</option>
                  <option value="Supervisor">Supervisor</option>
                </select>
              </div>
            </div>

            <!-- Text input-->
            <div class="form-group">
              <label class="col-md-4 control-label" for="salary">Salary</label>
              <div class="col-md-4">
                <input id="salary" name="salary" type="text" value="${employee.salary ?: ''}" class="form-control input-md"></div>
              </div>

              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="phoneNumber">Phone Number</label>
                <div class="col-md-4">
                  <input id="phoneNumber" name="phoneNumber" type="text" value="${employee.phoneNumber ?: ''}" class="form-control input-md"></div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                  <label class="col-md-4 control-label" for="email">Email</label>
                  <div class="col-md-4">
                    <input id="email" name="email" type="text" value="${employee.email ?: ''}" class="form-control input-md"></div>
                  </div>

                  <!-- Text input-->
                  <div class="form-group">
                    <label class="col-md-4 control-label" for="dob">Date of Birth</label>
                    <div class="col-md-4">
                      <input id="dob" name="dob" type="date" value="${employee.dob ?: ''}" max="1997-12-31" min="1970-1-1" placeholder="" class="form-control input-md"></div>
                    </div>

                    <!-- Button -->
                    <div class="form-group">
                      <label class="col-md-4 control-label" for=""></label>
                      <div class="col-md-4">
                        <button id="" name="" class="btn btn-primary">Submit</button>
                      </div>
                    </div>

                  </fieldset>

                </g:form>
                <g:hasErrors bean="${this.employee}" class="panel panel-danger">
                  <div class="panel panel-danger">
                    <ul class="errors" role="alert">
                      <g:eachError bean="${this.employee}" var="error"><li class="text-danger" <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                  </g:eachError>
                </ul>
              </div>
            </g:hasErrors>
          </div>
        </body>
      </html>

grails-app/views/employee/edit.gsp
<!DOCTYPE html>
<html>
  <head>
    <meta name="layout" content="master"/>
    <title>Add Employee</title>
  </head>
  <body>
    <div class="col-md-8 col-md-offset-2">

      <g:form resource="${this.employee}" class="form-horizontal" method="PUT">
        <fieldset>

          <!-- Form Name -->
          <legend>Edit ${employee.name} details</legend>

          <!-- Text input-->
          <div class="form-group">
            <label class="col-md-4 control-label" for="name">Name</label>
            <div class="col-md-4">
              <input id="name" name="name" type="text" value="${employee.name ?: ''}" class="form-control input-md" required></div>
            </div>

            <!-- Select Basic -->
            <div class="form-group">
              <label class="col-md-4 control-label" for="position">Position</label>
              <div class="col-md-4">
                <select required id="position" name="position" class="form-control">
                  <option value="Clerk">Clerk</option>
                  <option value="Manager">Manager</option>
                  <option value="Supervisor">Supervisor</option>
                </select>
              </div>
            </div>

            <!-- Text input-->
            <div class="form-group">
              <label class="col-md-4 control-label" for="salary">Salary</label>
              <div class="col-md-4">
                <input id="salary" name="salary" type="text" value="${employee.salary ?: ''}" class="form-control input-md"></div>
              </div>

              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="phoneNumber">Phone Number</label>
                <div class="col-md-4">
                  <input id="phoneNumber" name="phoneNumber" type="text" value="${employee.phoneNumber ?: ''}" class="form-control input-md"></div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                  <label class="col-md-4 control-label" for="email">Email</label>
                  <div class="col-md-4">
                    <input id="email" name="email" type="text" value="${employee.email ?: ''}" class="form-control input-md"></div>
                  </div>

                  <!-- Text input-->
                  <div class="form-group">
                    <label class="col-md-4 control-label" for="dob">Date of Birth</label>
                    <div class="col-md-4">
                      <input id="dob" name="dob" type="date" value="${employee.dob ?: ''}" max="1997-12-31" min="1970-1-1" placeholder="" class="form-control input-md"></div>
                    </div>

                    <!-- Button -->
                    <div class="form-group">
                      <label class="col-md-4 control-label" for=""></label>
                      <div class="col-md-4">
                        <button id="" name="" class="btn btn-primary">Submit</button>
                      </div>
                    </div>

                  </fieldset>

                </g:form>
                <g:hasErrors bean="${this.employee}" class="panel panel-danger">
                  <div class="panel panel-danger">
                    <ul class="errors" role="alert">
                      <g:eachError bean="${this.employee}" var="error"><li class="text-danger" <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                  </g:eachError>
                </ul>
              </div>
            </g:hasErrors>
          </div>
        </body>
      </html>

grails-app/views/employee/index.gsp
<!DOCTYPE html>
<html>
  <head>
    <meta name="layout" content="master"/>
    <title>Employee Index</title>
  </head>
  <body>
    <div class="col-md-8 col-md-offset-2">
      <legend>List of Employees</legend>
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <td>
              <b>No.</b>
            </td>
            <td>
              <b>Name</b>
            </td>
            <td>
              <b>Position</b>
            </td>
            <td>
              <b>Salary</b>
            </td>
            <td>
              <b>Phone Number</b>
            </td>
            <td>
              <b>Email</b>
            </td>
            <td>
              <b>Date of Birth</b>
            </td>
            <td>
              <b>Action</b>
            </td>
          </tr>
        </thead>
        <tbody>
          <g:each in="${emp}" var="p" status="i">
            <tr>
              <td>${i+1}</td>
              <td>${p.name}</td>
              <td>${p.position}</td>
              <td>${p.salary}</td>
              <td>${p.phoneNumber}</td>
              <td>${p.email}</td>
              <td>${p.dob}</td>
              <td>
                <a href="/employee/show/${p.id}" class="btn btn-xs btn-primary">Show</a>
              </td>
            </tr>
          </g:each>
        </tbody>
      </table>
    </div>
  </body>
</html>

grails-app/views/employee/show.gsp
<!DOCTYPE html>
<html>
  <head>
    <meta name="layout" content="master"/>
    <title>Employee Index</title>
  </head>
  <body>
    <div class="col-md-8 col-md-offset-2 ">
      <legend>${employee.name} details</legend>
        <div class="row" style="height:2em">
          <label class="col-md-4" for="" class="col-md-4">Name</label>
          <p  class="col-md-4" style="font-size:20px">${employee.name}</p>
        </div><hr>
        <div class="row" style="height:2em">
          <label class="col-md-4" for="">Position</label>
          <p class="col-md-4" style="font-size:20px">${employee.position}</p>
        </div><hr>
        <div class="row" style="height:2em">
          <label class="col-md-4" for="">Salary</label>
          <p class="col-md-4" style="font-size:20px">${employee.salary}</p>
        </div><hr>
        <div class="row" style="height:2em">
          <label class="col-md-4" for="">Phone Number</label>
          <p class="col-md-4" style="font-size:20px">${employee.phoneNumber}</p>
        </div><hr>
        <div class="row" style="height:2em">
          <label class="col-md-4" for="">Email</label>
          <p class="col-md-4" style="font-size:20px">${employee.email}</p>
        </div><hr>
        <div class="row" style="height:2em">
          <label class="col-md-4" for="">Date of Birth</label>
          <p class="col-md-4" class="col-md-4" style="font-size:20px">${employee.dob}</p>
        </div><hr>
        <a href="/employee/edit/${employee.id}" class="btn btn-warning">Update</a>
        <g:form resource="${this.employee}" method="DELETE" style="display:inline">
        <button type="submit" class="btn btn-danger" onclick="return confirm('Are you want to delete ${employee.name} sure?');">Delete</a>
      </g:form>
      </div>
  </body>
</html>

grails-app/views/layouts/main.gsp
<!doctype html>
<html lang="en" class="no-js">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>
        <g:layoutTitle default="Grails"/>
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    <asset:stylesheet src="application.css"/>

    <g:layoutHead/>
</head>
<body>

    <div class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/#">
                    <i class="fa grails-icon">
                        <asset:image src="grails-cupsonly-logo-white.svg"/>
                    </i> Grails
                </a>
            </div>
            <div class="navbar-collapse collapse" aria-expanded="false" style="height: 0.8px;">
                <ul class="nav navbar-nav navbar-right">
                    <g:pageProperty name="page.nav" />
                </ul>
            </div>
        </div>
    </div>

    <g:layoutBody/>

    <div class="footer" role="contentinfo"></div>

    <div id="spinner" class="spinner" style="display:none;">
        <g:message code="spinner.alt" default="Loading&hellip;"/>
    </div>

    <asset:javascript src="application.js"/>

</body>
</html>

grails-app/views/layouts/master.gsp
<!DOCTYPE html>
<html>
  <head>
    <title><g:layoutTitle default="Employee Management System"/></title>

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

      <g:layoutHead/>
    </head>

    <body style="padding-bottom:50em">

      <div class="" >
        <div class="navbar-static-top">
          <nav class="navbar navbar-default">
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/#"><span class="glyphicon glyphicon-user"></span> Employee Management System</a>
              </div>
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                  <li class="">
                    <a href="/#">Home
                      <span class="sr-only">(current)</span>
                    </a>
                  </li>
                  <li class="">
                    <a href="/employee/create">Add Employee</a>
                  </li>
                  <li class="">
                    <a href="/employee/index">Employee List</a>
                  </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li class="hidden-xs">
                    <a>
                      <span class="text-info">${println(new Date())}</span>
                    </a>
                  </li>
                </ul>
              </div>
              <!-- /.navbar-collapse -->
            </div>
            <!-- /.container-fluid -->
          </nav>
        </div>
      </div>

      <g:layoutBody/>
    </body>

    <footer class="footer navbar-fixed-bottom">
      <div style="background:white">
        <div class="container">
          <p>Created by
            <a href="fb.com/mr.shahlol" style="text-decoration: none">Abdulsalam Shahlol</a>
          </p>
        </div>
      </div>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </footer>
  </html>